# Generated by Django 4.2.24 on 2025-09-07 16:29

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("submissions", "0002_rename_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="stack_tags_json",
        ),
        migrations.AddField(
            model_name="submission",
            name="stack_tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
