# Generated by Django 4.2.24 on 2025-09-08 07:41

import apps.submissions.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0016_remove_execution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="birth_year",
            field=models.IntegerField(
                default=apps.submissions.models.current_year,
                validators=[django.core.validators.MinValueValidator(1995)],
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("flagged", "Flagged"),
                    ("removed", "Removed"),
                ],
                db_index=True,
                default="published",
                max_length=10,
            ),
        ),
    ]
